import os
path = os.getcwd()
print(f'path is : {path}')
files = os.listdir()
print(f"list of files in the directory : {files}/n")
#os.mkdir("FileOrganiser")
#print("new folder created")
exists = os.path.exists("fileproject/nfile.txt")
print(f"file exists : {exists}")
#check = os.listdir("pdfs")
#print(f"list of files in the directory : {check}/n")
os.system("calc")
print("calculator opened")
os.system("notepad")
print("notepad opened")